apiVersion: v1
kind: Service
metadata:
  name: open5gs-sgwu-svc-pool
  namespace: open5gs
  labels:
    epc-mode: sgw-u
spec:
  ports:
  - name: sxa
    port: 8805
    protocol: UDP
  - name: s1u
    port: 2152
#  clusterIP: None   
  selector:
    epc-mode: sgw-u      
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: StatefulSet
metadata:
  name: open5gs-sgw-u
  namespace: open5gs
  labels:
    epc-mode: sgw-u
spec:
  replicas: 1
  serviceName: "open5gs-sgw-u-svc-pool"
  selector:
    matchLabels:
      epc-mode: sgw-u
  template:
    metadata:
      labels:
        epc-mode: sgw-u
    spec:
      containers:
        - name: sgwu
          image: localhost:5000/open5gs-base:1.0
          imagePullPolicy: IfNotPresent
          command: ["/root/5g-assert/install/bin/open5gs-sgwud", "-c", "/root/5g-assert/install/etc/open5gs/sgwu.yaml"]
          volumeMounts:
            - name: open5gs-sgwu-config
              mountPath: /root/5g-assert/install/etc/open5gs/sgwu.yaml
              subPath: "sgwu.yaml"
      volumes:
        - name: open5gs-sgwu-config
          configMap:
            name: open5gs-sgwu-config
