apiVersion: v1
kind: ConfigMap
metadata:
  name: open5gs-upf-config
  namespace: open5gs
  labels:
    epc-mode: upf
data:
  upf.yaml: |
    logger:
        file: /var/log/open5gs/upf.log

    upf:
        pfcp:
           dev: eth0
        gtpu:
           dev: eth0
        subnet:
          - addr: 192.168.0.0/16
            apn: internet
        dns:
          - 8.8.8.8
          - 8.8.4.4
