apiVersion: v1
kind: Service
metadata:
  name: open5gs-webui
  namespace: open5gs
  labels:
    epc-mode: webui
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 3000
  selector:
    epc-mode: webui
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: open5gs-webui
  namespace: open5gs  
  labels:
    epc-mode: webui
spec:
  replicas: 1
  selector:
    matchLabels:
      epc-mode: webui
  template:
    metadata:
      labels:
        epc-mode: webui
    spec:
      containers:
      - name: webui
        imagePullPolicy: IfNotPresent
        image: localhost:5000/open5gs-webui
        command: ["node", "server/index.js"]
        ports:
        - containerPort: 3000
        env:
        - name: DB_URI
          value: "mongodb://172.17.93.97:27017/open5gs"
        - name: NODE_ENV
          value: "production"
        - name: HOSTNAME
          value: 0.0.0.0     
