apiVersion: v1
kind: ConfigMap
metadata:
  name: open5gs-amf-config
  namespace: open5gs
  labels:
    epc-mode: amf
data:
  amf.yaml: |
    logger:
        file: /var/log/open5gs/amf.log

    parameter:
        no_ipv6: true

    amf:
        sbi:
           dev: eth0
           port: 7777
        ngap:
           dev: eth0
        guami:
          - plmn_id:
              mcc: 432
              mnc: 45
            amf_id:
              region: 2
              set: 1
        tai:
          - plmn_id:
              mcc: 432
              mnc: 45
            tac: 1
        plmn_support:
           - plmn_id:
              mcc: 435
              mnc: 45
             s_nssai:
              - sst: 1
        security:
            integrity_order : [ NIA2, NIA1, NIA0 ]
            ciphering_order : [ NEA0, NEA1, NEA2 ]
        network_name:
            full: Open5GS
        amf_name: open5gs-amf

    nrf:
        sbi:
          - name: "open5gs-nrf-svc-pool"
            port: 7777
