apiVersion: v1
kind: Service
metadata:
  name: open5gs-amf-svc-pool
  namespace: open5gs
  labels:
    epc-mode: amf
spec:
  type: LoadBalancer
  ports:
  - name: amf-ngap-t 
    port: 38412
    protocol: TCP
  - name: amf-ngap-u
    port: 38412
    protocol: UDP
  - name: amf-sbi-t
    port: 7777
    protocol: TCP
  - name: amf-sbi-u
    port: 7777
    protocol: UDP
  selector:  
    epc-mode: amf        
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: open5gs-amf
  namespace: open5gs
  labels:
    epc-mode: amf
spec:
  replicas: 1
  serviceName: "open5gs-amf-svc-pool"
  selector:
    matchLabels:
      epc-mode: amf
  template:
    metadata:
      labels:
        epc-mode: amf
    spec:
      containers:
        - name: amf
          image: reg.open5gs.local/open5gs/open5gs-base:1.0
          imagePullPolicy: IfNotPresent
          command: ["/root/5g-assert/install/bin/open5gs-amfd", "-c", "/root/5g-assert/install/etc/open5gs/amf.yaml"]
          volumeMounts:
          - name: open5gs-amf-config
            mountPath: /root/5g-assert/install/etc/open5gs/amf.yaml
            subPath: "amf.yaml"          
      volumes:
        - name: open5gs-amf-config
          configMap:
            name: open5gs-amf-config
