apiVersion: v1
kind: Service
metadata:
  name: open5gs-pcrf-svc-pool
  namespace: open5gs
  labels:
    epc-mode: pcrf
spec:
  ports:
  - name: gx
    port: 3868
    protocol: TCP
  selector:
    epc-mode: pcrf
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: open5gs-pcrf
  namespace: open5gs
  labels:
    epc-mode: pcrf
spec:
  replicas: 1
  serviceName: "open5gs-pcrf-svc-pool"
  selector:
    matchLabels:
      epc-mode: pcrf
  template:
    metadata:
      labels:
        epc-mode: pcrf
    spec:
      containers:
        - name: pcrf
          image: reg.open5gs.local/open5gs/open5gs-base:1.0
#          image: localhost:5000/open5gs-base:1.0
          imagePullPolicy: Always
          command: ["/root/5g-assert/install/bin/open5gs-pcrfd", "-c", "/root/5g-assert/install/etc/open5gs/pcrf.yaml"]
          volumeMounts:
          - name: open5gs-pcrf-config
            mountPath: /root/5g-assert/install/etc/open5gs/pcrf.yaml
            subPath: "pcrf.yaml"
          - name: open5gs-pcrf-diameter
            mountPath: /root/5g-assert/install/etc/open5gs/diameter-pcrf.conf
            subPath: "diameter-pcrf.conf"            
      volumes:
        - name: open5gs-pcrf-config
          configMap:
            name: open5gs-pcrf-config
        - name: open5gs-pcrf-diameter
          configMap:
            name: open5gs-pcrf-diameter            
