
apiVersion: v1
kind: Service
metadata:
  name: open5gs-mme-svc-pool
  namespace: open5gs
  labels:
    epc-mode: mme
spec:
  type: LoadBalancer
  ports:
  - name: s6a
    port: 3868
    protocol: SCTP
  - name: s6a-5868
    port: 5868
    protocol: SCTP
  - name: s1-mme
    port: 36412
    targetPort: 36412
    protocol: SCTP
  - name: s11 
    port: 2123
    protocol: UDP
  - name: port80
    port: 80
    protocol: TCP
  - name: port8080
    port: 8080
  selector:
    epc-mode: mme
  sessionAffinity: ClientIP
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1
kind: StatefulSet
metadata:
  name: open5gs-mme
  namespace: open5gs
  labels:
    epc-mode: mme
spec:
  replicas: 1
  serviceName: "open5gs-mme-svc-pool"
  selector:
    matchLabels:
      epc-mode: mme
  template:
    metadata:
      labels:
        epc-mode: mme
#      annotations:
#        cni.projectcalico.org/ipv4pools: '["mme-ippool"]'
    spec:
      containers:
        - name: mme
          image: reg.open5gs.local/open5gs/open5gs-base:2.0
          imagePullPolicy: Always
          command: ["/bin/sh"]
          args: ["-c", "echo 1 > /etc/recovery_counter.txt ; /root/5g-assert/install/bin/open5gs-mmed -c /root/5g-assert/install/etc/open5gs/mme.yaml;"]
          volumeMounts:
          - name: open5gs-mme-config
            mountPath: /root/5g-assert/install/etc/open5gs/mme.yaml
            subPath: "mme.yaml"
          - name: open5gs-mme-diameter
            mountPath: /root/5g-assert/install/lib/x86_64-linux-gnu/freeDiameter/mme.conf
            subPath: "diameter-mme.conf"
          - name: mme-persistent-storage
            mountPath: /var/log/open5gs
        - name: my-ip
          image: reg.open5gs.local/cloudnativelabs/whats-my-ip:latest
      volumes:
        - name: open5gs-mme-config
          configMap:
            name: open5gs-mme-config
        - name: open5gs-mme-diameter
          configMap:
            name: open5gs-mme-diameter
        - name: mme-persistent-storage
          persistentVolumeClaim:
            claimName: hss-claim
