apiVersion: v1
kind: ConfigMap
metadata:
  name: open5gs-mme-config
  namespace: open5gs
  labels:
    epc-mode: mme
data:
  mme.yaml: |
    logger:
        file: /var/log/open5gs/mme.log
    
    parameter:
    
    mme:
        freeDiameter: /root/5g-assert/install/lib/x86_64-linux-gnu/freeDiameter/mme.conf
        s1ap:
           dev: eth0
        gtpc:
           dev: eth0
        gummei:
          plmn_id:
            mcc: 432
            mnc: 45
          mme_gid: 2
          mme_code: 1
        tai:
          plmn_id:
            mcc: 432
            mnc: 45
          tac: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]
        security:
            integrity_order : [ EIA1, EIA2, EIA0 ]
            ciphering_order : [ EEA0, EEA1, EEA2 ]
        network_name:
            full: Zcore
        mme_name: k8-mme
    sgw:
        gtpc:
          - name: "open5gs-sgwc-svc-pool"
    smf:
        gtpc:
          - name: "open5gs-smf-svc-pool"
#    max:
#      ue: 8192
#       mgmt_request_path: tcp://172.17.125.3:6001
#       mgmt_response_path: tcp://172.17.125.3:6002
